VIA_ENABLE         = yes
VIAL_ENABLE        = yes
VIALRGB_ENABLE     = yes
ENCODER_MAP_ENABLE = yes
SERIAL_DRIVER = vendor
MCU = RP2040
BOOTLOADER = rp2040
FIRMWARE_FORMAT = uf2  # Generates a .uf2 file for easy flashing
FLASHER = rp2040
VIAL_ENABLE = yes
VIAL_COMBO_ENABLE = yes  # Enables combo key support in Vial
